from typing import Protocol

from ..snapshot import Snapshot


class VolumePort(Protocol):
    async def set_volume(self, level: float) -> None: ...
    async def get_volume(self) -> float: ...


class StateExportPort(Protocol):
    async def publish(self, snapshot: Snapshot) -> None: ...


class VolumeFeedbackPort(Protocol):
    async def sync_volume(self, level: float) -> None: ...


class SourceControlPort(Protocol):
    async def play(self) -> None: ...
    async def pause(self) -> None: ...
    async def stop(self) -> None: ...
    async def next_track(self) -> None: ...
    async def previous_track(self) -> None: ...
    async def seek(self, position_s: float) -> None: ...
